In [1]:
import pandas as pd
import numpy as np

In [2]:
data_1 = pd.read_csv("resume_text.csv")
data_1 = data_1.drop('Unnamed: 0', axis=1)
data_1['fontname'] = data_1['fontname'].astype('category')

In [3]:
data_2 = pd.read_csv("new_resumes_to_add.csv")
data_2 = data_2.drop('Unnamed: 0', axis=1)
data_2['fontname'] = data_2['fontname'].astype('category')

In [4]:
data_2["label"] = data_2["label"].replace("0", np.nan)

In [5]:
data_2["label"].value_counts()

label
PERSONAL          41
EXPERIENCE        27
SKILLS            14
EDUCATION         11
CERTIFICATIONS     3
Name: count, dtype: int64

In [6]:
data_2

,word,width,height,left_distance,bottom_distance,right_distance,top_distance,fontname,fontsize,label
0,Senior,30.152540,10.148936,232.791220,48.207446,262.943760,38.058510,AAAAAA+Rubik-Regular,10.148936,NaN
1,Business,42.564723,10.148936,265.206982,48.207446,307.771706,38.058510,AAAAAA+Rubik-Regular,10.148936,NaN
2,Analyst,35.429991,10.148936,309.994335,48.207446,345.424325,38.058510,AAAAAA+Rubik-Regular,10.148936,NaN
3,|,2.344404,10.148936,347.920971,48.207446,350.265376,38.058510,AAAAAA+Rubik-Regular,10.148936,NaN
4,Data,22.033372,10.148936,352.762026,48.207446,374.795398,38.058510,AAAAAA+Rubik-Regular,10.148936,NaN
...,...,...,...,...,...,...,...,...,...,...
3890,UAVs/UGVs).,57.494050,8.880319,38.692819,171.504747,96.186869,162.624428,CAAAAA+Inter-Regular,8.880319,NaN
3891,www.enhancv.com,62.291077,6.977394,41.864361,811.696821,104.155438,804.719427,CAAAAA+Inter-Regular,6.977394,NaN
3892,​,63.430850,63.430850,485.246004,839.546928,548.676854,776.116078,DAAAAA+resumeicons,63.430850,NaN
3893,Powered,28.900681,6.977394,434.501324,810.428204,463.402005,803.450810,CAAAAA+Inter-Regular,6.977394,NaN
3894,by,8.077522,6.977394,465.364397,810.428204,473.441919,803.450810,CAAAAA+Inter-Regular,6.977394,NaN

In [7]:
data = pd.concat([data_1, data_2], axis=0)

In [8]:
data.to_csv("resume_text.csv")

In [9]:
data["fontname"].value_counts()

fontname
BAAAAA+Inter-Regular                    1043
TimesNewRomanPSMT                        491
BAAAAA+OpenSans-Regular                  440
CAAAAA+Inter-Regular                     414
BAAAAA+MerriweatherLight18pt-Regular     406
                                        ...
BCDFEE+Avenir Next LT Pro,Bold             2
BCDEEE+Calibri-Bold                        2
CAAAAA+OpenSans-SemiBold                   2
WPFIDQ+TimesNewRomanPS-BoldMT              1
GORODB+TimesNewRomanPSMT                   1
Name: count, Length: 86, dtype: int64

In [10]:
data.dtypes

word                object
width              float64
height             float64
left_distance      float64
bottom_distance    float64
right_distance     float64
top_distance       float64
fontname            object
fontsize           float64
label               object
dtype: object

In [11]:
import spacy

In [12]:
nlp = spacy.load("en_core_web_sm")

W0306 17:05:59.610000 21828 site-packages\torch\distributed\elastic\multiprocessing\redirects.py:29] NOTE: Redirects are currently not supported in Windows or MacOs.

In [13]:
def word_to_vector(word):
    token = nlp(word)
    if token.has_vector:
        return token.vector
    else:
        # fallback for unknown words
        return np.zeros(300)

In [14]:
data['word'] = data['word'].apply(lambda x: word_to_vector(x))

In [15]:
vectorized_matrix = np.vstack(data['word'].values)
vectorized_matrix

array([[-0.951727  ,  0.95861304,  0.10500178, ..., -0.09028675,
        -0.49487162, -0.10355535],
       [-1.1149569 , -0.71303105,  0.7316609 , ...,  0.03929154,
        -0.8506578 ,  0.8752701 ],
       [-0.65856814, -0.61548555,  0.75911665, ..., -0.4805591 ,
        -0.54742825,  0.6536298 ],
       ...,
       [-1.5167557 , -0.39425257,  1.1220833 , ...,  0.535821  ,
        -0.9077779 ,  1.5336257 ],
       [ 0.42908424,  0.48055983, -0.23175609, ...,  0.8160704 ,
        -0.5793117 ,  0.10061955],
       [ 0.47492915, -0.6748308 ,  1.5062785 , ...,  1.0690808 ,
        -0.7549179 ,  0.8031944 ]], dtype=float32)

In [16]:
vectorized_df = pd.DataFrame(vectorized_matrix, index=data.index)
vectorized_df.columns = [f"vec_{i}" for i in range(vectorized_df.shape[1])]
vectorized_df

,vec_0,vec_1,vec_2,vec_3,vec_4,vec_5,vec_6,vec_7,vec_8,vec_9,...,vec_86,vec_87,vec_88,vec_89,vec_90,vec_91,vec_92,vec_93,vec_94,vec_95
0,-0.951727,0.958613,0.105002,1.112468,0.085638,-0.000849,1.114668,-0.105625,-0.307489,-0.359935,...,0.365579,0.096130,-0.374057,0.087240,-0.647736,-0.224829,1.525850,-0.090287,-0.494872,-0.103555
1,-1.114957,-0.713031,0.731661,0.351736,-0.057057,-0.415272,0.298382,0.787931,-0.495942,-0.295677,...,0.438323,0.136332,-0.207950,0.664034,-0.405884,0.831179,0.339219,0.039292,-0.850658,0.875270
2,-0.658568,-0.615486,0.759117,0.707565,0.218263,-0.771381,0.504122,1.811165,-0.929661,0.000416,...,0.957630,0.162773,-0.992980,0.532491,-0.780526,0.536946,1.226428,-0.480559,-0.547428,0.653630
3,-0.289157,0.424944,0.675534,0.758927,0.464087,-0.314538,1.461722,1.082651,-0.755823,-0.326815,...,0.269811,-0.039991,-0.133173,1.002280,-1.081869,0.547621,1.075723,-0.274464,-0.065403,0.185437
4,-0.791119,1.334212,0.635747,-0.211629,2.719424,-0.478058,-0.344881,-0.501575,0.073267,0.052321,...,-0.243623,0.031197,-0.291087,1.070206,0.059644,0.257148,0.249240,0.551616,-0.665604,-0.044459
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3890,-0.588772,0.324213,-0.126970,-0.482286,0.977973,1.127518,-0.145935,0.732534,0.092719,-0.230475,...,0.002214,1.044592,-0.788750,1.135214,-0.484495,0.816288,0.438590,-0.570673,-0.330720,-0.164118
3891,-1.407663,0.415866,0.435777,-1.197455,1.532793,-0.967413,-0.445946,0.704069,-0.529488,0.107601,...,-0.461022,0.580138,-0.810776,1.337947,0.261478,0.878072,-0.234321,-0.053341,-0.300221,1.234673
3892,-1.516756,-0.394253,1.122083,0.913133,1.370946,-0.535903,-0.084522,0.263449,-0.016879,-0.899116,...,1.236326,0.723781,-0.735596,1.842647,0.076017,0.033983,-0.220087,0.535821,-0.907778,1.533626
3893,0.429084,0.480560,-0.231756,0.403098,-0.596111,-0.295604,-0.451253,0.712904,-0.674913,-1.052410,...,1.265678,0.607335,1.496975,-0.277318,-0.081939,0.428885,-0.491797,0.816070,-0.579312,0.100620
3894,0.474929,-0.674831,1.506279,0.102446,-0.222110,-0.662399,-0.127342,-1.193003,0.147501,0.397514,...,-0.540776,0.977806,-0.529710,1.835962,-0.946140,0.008873,0.323602,1.069081,-0.754918,0.803194

In [17]:
meta_df = data.drop(columns=['word'])
data_vec = pd.concat([vectorized_df, meta_df], axis=1)
data_vec

,vec_0,vec_1,vec_2,vec_3,vec_4,vec_5,vec_6,vec_7,vec_8,vec_9,...,vec_95,width,height,left_distance,bottom_distance,right_distance,top_distance,fontname,fontsize,label
0,-0.951727,0.958613,0.105002,1.112468,0.085638,-0.000849,1.114668,-0.105625,-0.307489,-0.359935,...,-0.103555,130.392400,45.025000,54.050000,102.167050,184.442400,57.142050,BCDFEE+BookAntiqua,45.025000,PERSONAL
1,-1.114957,-0.713031,0.731661,0.351736,-0.057057,-0.415272,0.298382,0.787931,-0.495942,-0.295677,...,0.875270,154.931025,45.025000,199.400000,102.167050,354.331025,57.142050,BCDFEE+BookAntiqua,45.025000,PERSONAL
2,-0.658568,-0.615486,0.759117,0.707565,0.218263,-0.771381,0.504122,1.811165,-0.929661,0.000416,...,0.653630,96.636100,16.225000,54.050000,120.507250,150.686100,104.282250,BCDEEE+ArialMT,16.225000,NaN
3,-0.289157,0.424944,0.675534,0.758927,0.464087,-0.314538,1.461722,1.082651,-0.755823,-0.326815,...,0.185437,83.034600,13.800000,64.875000,181.377000,147.909600,167.577000,BCDGEE+BookAntiqua-Bold,13.800000,PERSONAL
4,-0.791119,1.334212,0.635747,-0.211629,2.719424,-0.478058,-0.344881,-0.501575,0.073267,0.052321,...,-0.044459,21.858600,10.200000,64.875000,202.092000,86.733600,191.892000,BCDEEE+ArialMT,10.200000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3890,-0.588772,0.324213,-0.126970,-0.482286,0.977973,1.127518,-0.145935,0.732534,0.092719,-0.230475,...,-0.164118,57.494050,8.880319,38.692819,171.504747,96.186869,162.624428,CAAAAA+Inter-Regular,8.880319,NaN
3891,-1.407663,0.415866,0.435777,-1.197455,1.532793,-0.967413,-0.445946,0.704069,-0.529488,0.107601,...,1.234673,62.291077,6.977394,41.864361,811.696821,104.155438,804.719427,CAAAAA+Inter-Regular,6.977394,NaN
3892,-1.516756,-0.394253,1.122083,0.913133,1.370946,-0.535903,-0.084522,0.263449,-0.016879,-0.899116,...,1.533626,63.430850,63.430850,485.246004,839.546928,548.676854,776.116078,DAAAAA+resumeicons,63.430850,NaN
3893,0.429084,0.480560,-0.231756,0.403098,-0.596111,-0.295604,-0.451253,0.712904,-0.674913,-1.052410,...,0.100620,28.900681,6.977394,434.501324,810.428204,463.402005,803.450810,CAAAAA+Inter-Regular,6.977394,NaN
3894,0.474929,-0.674831,1.506279,0.102446,-0.222110,-0.662399,-0.127342,-1.193003,0.147501,0.397514,...,0.803194,8.077522,6.977394,465.364397,810.428204,473.441919,803.450810,CAAAAA+Inter-Regular,6.977394,NaN

In [18]:
from category_encoders import OrdinalEncoder
import joblib

In [19]:
encoder = OrdinalEncoder()

encoder.fit(data['fontname'])

OrdinalEncoder(cols=['fontname'],
               mapping=[{'col': 'fontname', 'data_type': dtype('O'),
                         'mapping': BCDFEE+BookAntiqua                1
BCDEEE+ArialMT                    2
BCDGEE+BookAntiqua-Bold           3
BCDHEE+BookAntiqua                4
BCDJEE+ArialMT                    5
                                 ..
SymbolMT                         83
CFCIIJ+TimesNewRomanPS-BoldMT    84
BAAAAA+Rubik-Regular             85
CAAAAA+Inter-Regular             86
NaN                              -2
Length: 87, dtype: int64}])

In [20]:
data_vec['fontname'] = encoder.transform(data['fontname'])

encoder = joblib.dump(encoder, '../models/ordinal_encoder.pkl')

In [21]:
encoder = OrdinalEncoder()

encoder.fit(data_vec[['label']])

OrdinalEncoder(cols=['label'],
               mapping=[{'col': 'label', 'data_type': dtype('O'),
                         'mapping': PERSONAL          1
EDUCATION         2
SKILLS            3
EXPERIENCE        4
CERTIFICATIONS    5
NaN               6
dtype: int64}])

In [22]:
data_vec['label'] = encoder.transform(data_vec['label'])

encoder = joblib.dump(encoder, '../models/resume_label_encoder.pkl')

In [23]:
data_vec["label"].value_counts()

label
6    6501
1     104
4      39
3      27
2      22
5       3
Name: count, dtype: int64

In [24]:
data_vec.to_csv("dataset.csv")